### PR TITLE
Fix command script

### PR DESCRIPTION
**Pull request by kulovan**
This PR contains:
- Fix of bash script syntax error. Relates to #1 .
- Use `draft` field of repo metadata. Relates to #2.
- Extract command to a separate bash script.

### CODE REVIEW

**Comment by whyayen** [comment]
@kulovan 

The script file seems couldn't be loaded successfully.  The CircleCI response:
```
/bin/bash: ./scripts/check-skippable-pr.sh: No such file or directory
```

image

Should I change structure of project to `@orb.yml` structure like this [document](https://circleci.com/docs/2.0/orb-author/)?

**Comment by kulovan** [comment]
🤔 When and what is executed here? If you have time we can try setting up a pipeline for this orb.

**Comment by whyayen** [comment]
> 🤔 When and what is executed here? If you have time we can try setting up a pipeline for this orb.

I'll test it and setup a CI on this weekend. 🙏

**Comment by whyayen** [comment]
@kulovan I changed my project structure to follow [Orb Project Template](https://github.com/CircleCI-Public/Orb-Project-Template/blob/master/src/jobs/hello.yml) in the commit: [157aca0](https://github.com/whyayen/bye-github-draft/pull/3/commits/157aca07a971693eb762e1552686ab285c1c1c78).

 I’m very grateful for the contributions you’ve done for me. That helps me a lot. I would merge it and publish a v0.0.2. 🙏🏾

**Comment by whyayen** [comment]
@kulovan You could see my running result in this PR: https://github.com/whyayen/my-typescript-playground/pull/6. The orb version is the [157aca0](https://github.com/whyayen/bye-github-draft/pull/3/commits/157aca07a971693eb762e1552686ab285c1c1c78) version. It runs as our expected 👍🏾 .

**Comment by kulovan** [comment]
> @kulovan I changed my project structure to follow [Orb Project Template](https://github.com/CircleCI-Public/Orb-Project-Template/blob/master/src/jobs/hello.yml) in the commit: [157aca0](https://github.com/whyayen/bye-github-draft/pull/3/commits/157aca07a971693eb762e1552686ab285c1c1c78).
> 
> I’m very grateful for the contributions you’ve done for me. That helps me a lot. I would merge it and publish a v0.0.2. 🙏🏾

Your welcome! This is a useful orb you have created. It is even a good improvement of [artsy/skip-wip-ci@0.3.0](artsy/skip-wip-ci@0.3.0). Unfortunately, CircleCI does not have a default functionality which I think is important. 
[We](https://www.tier.app/en/) will use this orb for one of our repositories. Thank you for making this happen, keep up the good work! 👍👍

**Pull request merged**
